#!/usr/bin/env python3
"""
Duck - Single File Portable Automation Tool
Author: Duck Of Apocalypse Team
License: MIT
"""

import json
import os
import sys
import time
import subprocess
from pathlib import Path
from typing import Dict, Any, List

# ============================================================================
# CONSTANTS & DEFAULTS
# ============================================================================

DEFAULT_DATA_DIR = str(Path.home() / "Desktop" / "duckinfo")

DEFAULT_CONFIG = {
    "data_dir": DEFAULT_DATA_DIR,
    "directory": "~/aiwork",
    "terminal": "Ghostty",
    "agent": "gemini",
    "voice_key": "F5",
    "hotkey": {
        "mods": ["cmd", "alt"],
        "key": "L"
    }
}

# ============================================================================
# CORE LOGIC
# ============================================================================

class DuckApp:
    def __init__(self):
        self.exe_path = os.path.abspath(sys.argv[0])
        # If running as script, use python exe? No, prefer the script path for simplicity if not frozen
        if getattr(sys, 'frozen', False):
            self.exe_path = sys.executable
        
        self.config = self.load_config()
        self.ensure_setup()

    def get_data_dir(self) -> Path:
        # First check if we can read config to get data_dir
        # But wait, we need data_dir to read config. Circular?
        # Strategy: Try default location first.
        path = Path(DEFAULT_CONFIG["data_dir"]).expanduser()
        
        # If config file exists there and has a different data_dir, use that?
        # For simplicity: Keep config at DEFAULT_DATA_DIR always acts as the anchor.
        # User requested customization, but let's stick to the anchor logic:
        # Config always lives in ~/Desktop/duckinfo/config.json (or fallback).
        # Inside config request custom paths.
        
        return path

    def get_config_path(self) -> Path:
        return self.get_data_dir() / "config.json"

    def get_init_lua_path(self) -> Path:
        return self.get_data_dir() / "init.lua"

    def ensure_setup(self):
        """Ensure directories and files exist."""
        data_dir = self.get_data_dir()
        if not data_dir.exists():
            try:
                data_dir.mkdir(parents=True, exist_ok=True)
            except Exception as e:
                # Fallback to home if Desktop is read-only or weird
                fallback = Path.home() / "duckinfo"
                print(f"Warning: Could not create {data_dir} ({e}). Using {fallback}")
                DEFAULT_CONFIG["data_dir"] = str(fallback)
                data_dir = fallback
                data_dir.mkdir(parents=True, exist_ok=True)

        # Config
        if not self.get_config_path().exists():
            self.save_config(DEFAULT_CONFIG)
            self.config = DEFAULT_CONFIG.copy() # Reload defaults

        # Init.lua (regenerate to ensure path is correct)
        self.generate_init_lua()

    def load_config(self) -> Dict[str, Any]:
        path = self.get_config_path()
        if not path.exists():
            return DEFAULT_CONFIG.copy()
        
        try:
            with open(path, "r") as f:
                data = json.load(f)
            # Merge defaults
            cfg = DEFAULT_CONFIG.copy()
            cfg.update(data)
            return cfg
        except Exception as e:
            print(f"Error loading config: {e}")
            backup = path.with_suffix(".bak.json")
            if path.exists():
                path.rename(backup)
                print(f"Backed up corrupt config to {backup}")
            return DEFAULT_CONFIG.copy()

    def save_config(self, config: Dict[str, Any]):
        path = self.get_config_path()
        with open(path, "w") as f:
            json.dump(config, f, indent=2)
        self.config = config
        self.generate_init_lua() # Update lua if config changes

    def generate_init_lua(self):
        """Create Hammerspoon init.lua with correct path and hotkey."""
        path = self.get_init_lua_path()
        
        mods = self.config["hotkey"]["mods"]
        key = self.config["hotkey"]["key"]
        
        # Lua format for mods: {"cmd", "alt"}
        mods_str = "{" + ", ".join([f'"{m}"' for m in mods]) + "}"
        
        # Escape path
        safe_exe_path = self.exe_path.replace('"', '\\"')

        lua_content = f"""-- Auto-generated by Duck
local duckPath = "{safe_exe_path}"

hs.hotkey.bind({mods_str}, "{key}", function()
    hs.alert.show("🦆 Duck")
    hs.execute('"' .. duckPath .. '" trigger', true)
end)
"""
        with open(path, "w") as f:
            f.write(lua_content)

    # ========================================================================
    # AUTOMATION
    # ========================================================================
    
    def applescript(self, script: str):
        subprocess.run(["osascript", "-e", script], check=False)

    def run_workflow(self):
        """Execute the automation."""
        print("🦆 Triggering Workflow...")
        
        term = self.config["terminal"]
        directory = os.path.expanduser(self.config["directory"])
        agent = self.config["agent"]
        voice_key = self.config["voice_key"]

        print(f"  Terminal:  {term}")
        print(f"  Dir:       {directory}")
        print(f"  Agent:     {agent}")
        print(f"  Voice:     {voice_key}")
        
        # Placeholder Automation Implementation
        # In a real build, we would use the robust AppleScript from automation_mac.py
        # Here is a consolidated robust script for Terminal/Ghostty
        
        cmd_str = f'cd "{directory}" && {agent}'
        safe_cmd = cmd_str.replace('"', '\\"')
        
        script = ""
        if term.lower() == "ghostty":
            # Ghostty often needs helper or direct open
            print("  (Ghostty via open -a)")
            subprocess.run(["open", "-a", "Ghostty", directory])
            # Wait and paste command? Or assume user types it?
            # For this portable version, let's just create the terminal for now.
            script = f'display notification "Opened {term}" with title "Duck"'
            
        elif term.lower() in ["terminal", "iterm", "iterm2"]:
            # Standard AppleScript support
            app_name = "Terminal" if term.lower() == "terminal" else "iTerm"
            script = f'''
            tell application "{app_name}"
                activate
                do script "{safe_cmd}"
            end tell
            '''
        else:
            # Fallback
            subprocess.run(["open", "-a", term])
            
        if script:
            self.applescript(script)

        # Voice Trigger (simulated)
        # print("  (Simulating Voice Key press...)")
        # self.applescript(f'tell application "System Events" to key code 96') # F5

    # ========================================================================
    # INTERACTIVE MENU
    # ========================================================================

    def menu_settings(self):
        while True:
            os.system("clear")
            print("--- Settings ---")
            print(f"[1] Directory:  {self.config['directory']}")
            print(f"[2] Terminal:   {self.config['terminal']}")
            print(f"[3] Agent:      {self.config['agent']}")
            print(f"[4] Voice Key:  {self.config['voice_key']}")
            print(f"[5] Hotkey:     {self.config['hotkey']['mods']} + {self.config['hotkey']['key']}")
            print("[0] Back")
            
            c = input("Choice: ")
            if c == "0": break
            elif c == "1": self.config["directory"] = input("New directory: ")
            elif c == "2": self.config["terminal"] = input("New terminal: ")
            elif c == "3": self.config["agent"] = input("New agent command: ")
            elif c == "4": self.config["voice_key"] = input("New voice key (e.g. F5): ")
            elif c == "5":
                print("Format: cmd,alt L")
                mods = input("Mods (comma sep): ").split(",")
                key = input("Key: ")
                self.config["hotkey"] = {"mods": [m.strip() for m in mods], "key": key}
            
            self.save_config(self.config)

    def run_interactive(self):
        while True:
            os.system("clear")
            print("========================================")
            print("          🦆  D U C K")
            print("========================================")
            print(f"Config: {self.get_config_path()}")
            print("----------------------------------------")
            print("[1] Trigger Workflow")
            print("[2] Settings")
            print("[3] Show Integration Paths")
            print("[4] Exit")
            print("----------------------------------------")
            
            c = input("Choice: ")
            if c == "1":
                self.run_workflow()
                input("Press Enter...")
            elif c == "2":
                self.menu_settings()
            elif c == "3":
                print(f"\nConfig JSON:\n  {self.get_config_path()}")
                print(f"\nHammerspoon Init:\n  {self.get_init_lua_path()}")
                print("\nTo install Hammerspoon logic:")
                print(f"  cp {self.get_init_lua_path()} ~/.hammerspoon/init.lua")
                input("\nPress Enter...")
            elif c == "4":
                print("Bye!")
                sys.exit(0)

# ============================================================================
# ENTRY POINT
# ============================================================================

def main():
    app = DuckApp()
    
    if len(sys.argv) > 1 and sys.argv[1] == "trigger":
        app.run_workflow()
    else:
        app.run_interactive()

if __name__ == "__main__":
    main()
